/*
 * Invoicetronic API
 *
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: support@invoicetronic.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Invoicetronic.Sdk.Model;
using Invoicetronic.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Invoicetronic.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DatiConvenzione
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DatiConvenzioneTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DatiConvenzione
        //private DatiConvenzione instance;

        public DatiConvenzioneTests()
        {
            // TODO uncomment below to create an instance of DatiConvenzione
            //instance = new DatiConvenzione();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DatiConvenzione
        /// </summary>
        [Fact]
        public void DatiConvenzioneInstanceTest()
        {
            // TODO uncomment below to test "IsType" DatiConvenzione
            //Assert.IsType<DatiConvenzione>(instance);
        }

        /// <summary>
        /// Test the property 'RiferimentoNumeroLinea'
        /// </summary>
        [Fact]
        public void RiferimentoNumeroLineaTest()
        {
            // TODO unit test for the property 'RiferimentoNumeroLinea'
        }

        /// <summary>
        /// Test the property 'IdDocumento'
        /// </summary>
        [Fact]
        public void IdDocumentoTest()
        {
            // TODO unit test for the property 'IdDocumento'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'NumItem'
        /// </summary>
        [Fact]
        public void NumItemTest()
        {
            // TODO unit test for the property 'NumItem'
        }

        /// <summary>
        /// Test the property 'CodiceCommessaConvenzione'
        /// </summary>
        [Fact]
        public void CodiceCommessaConvenzioneTest()
        {
            // TODO unit test for the property 'CodiceCommessaConvenzione'
        }

        /// <summary>
        /// Test the property 'CodiceCup'
        /// </summary>
        [Fact]
        public void CodiceCupTest()
        {
            // TODO unit test for the property 'CodiceCup'
        }

        /// <summary>
        /// Test the property 'CodiceCig'
        /// </summary>
        [Fact]
        public void CodiceCigTest()
        {
            // TODO unit test for the property 'CodiceCig'
        }
    }
}
