/*
 * Invoicetronic API
 *
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1.12.0
 * Contact: info@invoicetronic.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Invoicetronic.Sdk.Client.FileParameter;
using OpenAPIDateConverter = Invoicetronic.Sdk.Client.OpenAPIDateConverter;

namespace Invoicetronic.Sdk.Model
{
    /// <summary>
    /// Reduced Send data for Update responses, containing only the essential fields.
    /// </summary>
    [DataContract(Name = "SendReduced")]
    public partial class SendReduced : IValidatableObject
    {
        /// <summary>
        /// Current SDI state of the invoice. Reflects the most recent update received from SDI.
        /// </summary>
        /// <value>Current SDI state of the invoice. Reflects the most recent update received from SDI.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LatestStateEnum
        {
            /// <summary>
            /// Enum Inviato for value: Inviato
            /// </summary>
            [EnumMember(Value = "Inviato")]
            Inviato = 1,

            /// <summary>
            /// Enum Consegnato for value: Consegnato
            /// </summary>
            [EnumMember(Value = "Consegnato")]
            Consegnato = 2,

            /// <summary>
            /// Enum NonConsegnato for value: NonConsegnato
            /// </summary>
            [EnumMember(Value = "NonConsegnato")]
            NonConsegnato = 3,

            /// <summary>
            /// Enum Scartato for value: Scartato
            /// </summary>
            [EnumMember(Value = "Scartato")]
            Scartato = 4,

            /// <summary>
            /// Enum AccettatoDalDestinatario for value: AccettatoDalDestinatario
            /// </summary>
            [EnumMember(Value = "AccettatoDalDestinatario")]
            AccettatoDalDestinatario = 5,

            /// <summary>
            /// Enum RifiutatoDalDestinatario for value: RifiutatoDalDestinatario
            /// </summary>
            [EnumMember(Value = "RifiutatoDalDestinatario")]
            RifiutatoDalDestinatario = 6,

            /// <summary>
            /// Enum ImpossibilitaDiRecapito for value: ImpossibilitaDiRecapito
            /// </summary>
            [EnumMember(Value = "ImpossibilitaDiRecapito")]
            ImpossibilitaDiRecapito = 7,

            /// <summary>
            /// Enum DecorrenzaTermini for value: DecorrenzaTermini
            /// </summary>
            [EnumMember(Value = "DecorrenzaTermini")]
            DecorrenzaTermini = 8,

            /// <summary>
            /// Enum AttestazioneTrasmissioneFattura for value: AttestazioneTrasmissioneFattura
            /// </summary>
            [EnumMember(Value = "AttestazioneTrasmissioneFattura")]
            AttestazioneTrasmissioneFattura = 9
        }


        /// <summary>
        /// Current SDI state of the invoice. Reflects the most recent update received from SDI.
        /// </summary>
        /// <value>Current SDI state of the invoice. Reflects the most recent update received from SDI.</value>
        [DataMember(Name = "latest_state", EmitDefaultValue = true)]
        public LatestStateEnum? LatestState { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SendReduced" /> class.
        /// </summary>
        /// <param name="identifier">SDI identifier..</param>
        /// <param name="prestatore">VAT number of the Cedente/Prestatore (vendor)..</param>
        /// <param name="metaData">Optional metadata, as json..</param>
        /// <param name="documents">The invoices included in the payload..</param>
        /// <param name="dateSent">When the invoice was sent to SDI..</param>
        /// <param name="latestState">Current SDI state of the invoice. Reflects the most recent update received from SDI..</param>
        public SendReduced(string identifier = default, string prestatore = default, Dictionary<string, string> metaData = default, List<DocumentData> documents = default, DateTime? dateSent = default, LatestStateEnum? latestState = default)
        {
            this.Identifier = identifier;
            this.Prestatore = prestatore;
            this.MetaData = metaData;
            this.Documents = documents;
            this.DateSent = dateSent;
            this.LatestState = latestState;
        }

        /// <summary>
        /// SDI identifier.
        /// </summary>
        /// <value>SDI identifier.</value>
        [DataMember(Name = "identifier", EmitDefaultValue = true)]
        public string Identifier { get; set; }

        /// <summary>
        /// VAT number of the Cedente/Prestatore (vendor).
        /// </summary>
        /// <value>VAT number of the Cedente/Prestatore (vendor).</value>
        [DataMember(Name = "prestatore", EmitDefaultValue = true)]
        public string Prestatore { get; set; }

        /// <summary>
        /// Optional metadata, as json.
        /// </summary>
        /// <value>Optional metadata, as json.</value>
        [DataMember(Name = "meta_data", EmitDefaultValue = true)]
        public Dictionary<string, string> MetaData { get; set; }

        /// <summary>
        /// The invoices included in the payload.
        /// </summary>
        /// <value>The invoices included in the payload.</value>
        [DataMember(Name = "documents", EmitDefaultValue = true)]
        public List<DocumentData> Documents { get; set; }

        /// <summary>
        /// When the invoice was sent to SDI.
        /// </summary>
        /// <value>When the invoice was sent to SDI.</value>
        [DataMember(Name = "date_sent", EmitDefaultValue = true)]
        public DateTime? DateSent { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendReduced {\n");
            sb.Append("  Identifier: ").Append(Identifier).Append("\n");
            sb.Append("  Prestatore: ").Append(Prestatore).Append("\n");
            sb.Append("  MetaData: ").Append(MetaData).Append("\n");
            sb.Append("  Documents: ").Append(Documents).Append("\n");
            sb.Append("  DateSent: ").Append(DateSent).Append("\n");
            sb.Append("  LatestState: ").Append(LatestState).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
