// <auto-generated>
/*
 * Invoicetronic API
 *
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: support@invoicetronic.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Invoicetronic.Sdk.Client;

namespace Invoicetronic.Sdk.Model
{
    /// <summary>
    /// Status
    /// </summary>
    public partial class Status : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Status" /> class.
        /// </summary>
        /// <param name="operationLeft">Operations (invoices and validations) left.</param>
        /// <param name="signatureLeft">Signatures left.</param>
        [JsonConstructor]
        public Status(Option<int?> operationLeft = default, Option<int?> signatureLeft = default)
        {
            OperationLeftOption = operationLeft;
            SignatureLeftOption = signatureLeft;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of OperationLeft
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> OperationLeftOption { get; private set; }

        /// <summary>
        /// Operations (invoices and validations) left.
        /// </summary>
        /// <value>Operations (invoices and validations) left.</value>
        [JsonPropertyName("operation_left")]
        public int? OperationLeft { get { return this.OperationLeftOption; } set { this.OperationLeftOption = new Option<int?>(value); } }

        /// <summary>
        /// Used to track the state of SignatureLeft
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> SignatureLeftOption { get; private set; }

        /// <summary>
        /// Signatures left.
        /// </summary>
        /// <value>Signatures left.</value>
        [JsonPropertyName("signature_left")]
        public int? SignatureLeft { get { return this.SignatureLeftOption; } set { this.SignatureLeftOption = new Option<int?>(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Status {\n");
            sb.Append("  OperationLeft: ").Append(OperationLeft).Append("\n");
            sb.Append("  SignatureLeft: ").Append(SignatureLeft).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Status" />
    /// </summary>
    public class StatusJsonConverter : JsonConverter<Status>
    {
        /// <summary>
        /// Deserializes json to <see cref="Status" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Status Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> operationLeft = default;
            Option<int?> signatureLeft = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "operation_left":
                            operationLeft = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "signature_left":
                            signatureLeft = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (operationLeft.IsSet && operationLeft.Value == null)
                throw new ArgumentNullException(nameof(operationLeft), "Property is not nullable for class Status.");

            if (signatureLeft.IsSet && signatureLeft.Value == null)
                throw new ArgumentNullException(nameof(signatureLeft), "Property is not nullable for class Status.");

            return new Status(operationLeft, signatureLeft);
        }

        /// <summary>
        /// Serializes a <see cref="Status" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="status"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Status status, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, status, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Status" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="status"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Status status, JsonSerializerOptions jsonSerializerOptions)
        {
            if (status.OperationLeftOption.IsSet)
                writer.WriteNumber("operation_left", status.OperationLeftOption.Value.Value);

            if (status.SignatureLeftOption.IsSet)
                writer.WriteNumber("signature_left", status.SignatureLeftOption.Value.Value);
        }
    }
}
