/*
 * Invoicetronic API
 *
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: support@invoicetronic.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Invoicetronic.Sdk.Api;
using Invoicetronic.Sdk.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Invoicetronic.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing LogApi
    /// </summary>
    public sealed class LogApiTests : ApiTestsBase
    {
        private readonly ILogApi _instance;

        public LogApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ILogApi>();
        }

        /// <summary>
        /// Test LogGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task LogGetAsyncTest()
        {
            Client.Option<int> companyId = default;
            Client.Option<string> endpoint = default;
            Client.Option<string> method = default;
            Client.Option<int> apiVerion = default;
            Client.Option<int> statusCode = default;
            Client.Option<DateTime> dateCreatedFrom = default;
            Client.Option<DateTime> dateCreatedTo = default;
            Client.Option<int> page = default;
            Client.Option<int> pageSize = default;
            Client.Option<string> sort = default;
            Client.Option<string> query = default;
            Client.Option<bool> success = default;
            Client.Option<DateTime> dateTimeFrom = default;
            Client.Option<DateTime> dateTimeTo = default;
            var response = await _instance.LogGetAsync(companyId, endpoint, method, apiVerion, statusCode, dateCreatedFrom, dateCreatedTo, page, pageSize, sort, query, success, dateTimeFrom, dateTimeTo);
            var model = response.Ok();
            Assert.IsType<List<Event>>(model);
        }

        /// <summary>
        /// Test LogIdGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task LogIdGetAsyncTest()
        {
            int id = default;
            var response = await _instance.LogIdGetAsync(id);
            var model = response.Ok();
            Assert.IsType<Event>(model);
        }
    }
}
