/*
 * Italian eInvoice API
 *
 * The Italian eInvoice API is a RESTful API that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1] (Interchange Service). The API is designed by Invoicetronic to be simple and easy to use, abstracting away the Interchange Service's complexity while still providing complete control over the invoice send/receive process. The API also provides advanced features and a rich toolchain, such as invoice validation, multiple upload methods, webhooks, event logs, CORS support, client SDKs for commonly used languages, and CLI tools.  For more information, see:  - [Invoicetronic website][2] - [Invoice API reference][3]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/ [3]: https://api.invoicetronic.com/invoice/v1/docs 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@invoicetronic.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Invoicetronic.eInvoice.Sdk.Model;
using Invoicetronic.eInvoice.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Invoicetronic.eInvoice.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DatiTrasmissione
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DatiTrasmissioneTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DatiTrasmissione
        //private DatiTrasmissione instance;

        public DatiTrasmissioneTests()
        {
            // TODO uncomment below to create an instance of DatiTrasmissione
            //instance = new DatiTrasmissione();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DatiTrasmissione
        /// </summary>
        [Fact]
        public void DatiTrasmissioneInstanceTest()
        {
            // TODO uncomment below to test "IsType" DatiTrasmissione
            //Assert.IsType<DatiTrasmissione>(instance);
        }

        /// <summary>
        /// Test the property 'IdTrasmittente'
        /// </summary>
        [Fact]
        public void IdTrasmittenteTest()
        {
            // TODO unit test for the property 'IdTrasmittente'
        }

        /// <summary>
        /// Test the property 'ProgressivoInvio'
        /// </summary>
        [Fact]
        public void ProgressivoInvioTest()
        {
            // TODO unit test for the property 'ProgressivoInvio'
        }

        /// <summary>
        /// Test the property 'FormatoTrasmissione'
        /// </summary>
        [Fact]
        public void FormatoTrasmissioneTest()
        {
            // TODO unit test for the property 'FormatoTrasmissione'
        }

        /// <summary>
        /// Test the property 'CodiceDestinatario'
        /// </summary>
        [Fact]
        public void CodiceDestinatarioTest()
        {
            // TODO unit test for the property 'CodiceDestinatario'
        }

        /// <summary>
        /// Test the property 'ContattiTrasmittente'
        /// </summary>
        [Fact]
        public void ContattiTrasmittenteTest()
        {
            // TODO unit test for the property 'ContattiTrasmittente'
        }

        /// <summary>
        /// Test the property 'PecDestinatario'
        /// </summary>
        [Fact]
        public void PecDestinatarioTest()
        {
            // TODO unit test for the property 'PecDestinatario'
        }
    }
}
