/*
 * Italian Invoice API
 *
 * The Italian Invoice API is a RESTful API that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1] (Interchange Service). The API is designed by Invoicetronic to be simple and easy to use, abstracting away the Interchange Service's complexity while still providing complete control over the invoice send/receive process. The API also provides advanced features and a rich toolchain, such as invoice validation, multiple upload methods, webhooks, event logs, CORS support, client SDKs for commonly used languages, and CLI tools.  For more information, see:  - [Invoicetronic website][2] - [Invoice API reference][3]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/ [3]: https://api.invoicetronic.com/invoice/v1/docs 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@invoicetronic.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Invoicetronic.InvoiceApi.Client;
using Invoicetronic.InvoiceApi.Api;
// uncomment below to import models
//using Invoicetronic.InvoiceApi.Model;

namespace Invoicetronic.InvoiceApi.Test.Api
{
    /// <summary>
    ///  Class for testing ReceiveApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ReceiveApiTests : IDisposable
    {
        private ReceiveApi instance;

        public ReceiveApiTests()
        {
            instance = new ReceiveApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ReceiveApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ReceiveApi
            //Assert.IsType<ReceiveApi>(instance);
        }

        /// <summary>
        /// Test InvoiceV1ReceiveGet
        /// </summary>
        [Fact]
        public void InvoiceV1ReceiveGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? companyId = null;
            //string identifier = null;
            //bool? unread = null;
            //string committente = null;
            //string prestatore = null;
            //string fileName = null;
            //DateTime? lastUpdateFrom = null;
            //DateTime? lastUpdateTo = null;
            //DateTime? dateSentFrom = null;
            //DateTime? dateSentTo = null;
            //DateTime? documentDateFrom = null;
            //DateTime? documentDateTo = null;
            //string documentNumber = null;
            //int? page = null;
            //int? pageSize = null;
            //var response = instance.InvoiceV1ReceiveGet(companyId, identifier, unread, committente, prestatore, fileName, lastUpdateFrom, lastUpdateTo, dateSentFrom, dateSentTo, documentDateFrom, documentDateTo, documentNumber, page, pageSize);
            //Assert.IsType<List<Receive>>(response);
        }

        /// <summary>
        /// Test InvoiceV1ReceiveIdDelete
        /// </summary>
        [Fact]
        public void InvoiceV1ReceiveIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.InvoiceV1ReceiveIdDelete(id);
            //Assert.IsType<Receive>(response);
        }

        /// <summary>
        /// Test InvoiceV1ReceiveIdGet
        /// </summary>
        [Fact]
        public void InvoiceV1ReceiveIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int id = null;
            //var response = instance.InvoiceV1ReceiveIdGet(id);
            //Assert.IsType<Receive>(response);
        }
    }
}
